//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormChinh
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEN : DbContext
    {
        public DBEN()
            : base("name=DBEN")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LOAISANPHAM> LOAISANPHAMs { get; set; }
        public virtual DbSet<NHACUNGCAP> NHACUNGCAPs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblAccount> tblAccounts { get; set; }
        public virtual DbSet<tblChiTietHDBan> tblChiTietHDBans { get; set; }
        public virtual DbSet<tblChiTietHDNhap> tblChiTietHDNhaps { get; set; }
        public virtual DbSet<tblHang> tblHangs { get; set; }
        public virtual DbSet<tblHDBan> tblHDBans { get; set; }
        public virtual DbSet<tblHDNhap> tblHDNhaps { get; set; }
        public virtual DbSet<tblKhach> tblKhaches { get; set; }
        public virtual DbSet<tblNhanVien> tblNhanViens { get; set; }
    }
}
