//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormChinh
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccount
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public int Type { get; set; }
        public string Manhanvien { get; set; }
    
        public virtual tblNhanVien tblNhanVien { get; set; }
    }
}
