//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormChinh
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHDBan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHDBan()
        {
            this.tblChiTietHDBans = new HashSet<tblChiTietHDBan>();
        }
    
        public string MaHDBan { get; set; }
        public string Manhanvien { get; set; }
        public System.DateTime Ngayban { get; set; }
        public string Makhach { get; set; }
        public Nullable<double> Tongtien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietHDBan> tblChiTietHDBans { get; set; }
        public virtual tblKhach tblKhach { get; set; }
        public virtual tblNhanVien tblNhanVien { get; set; }
    }
}
