//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormChinh
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHang()
        {
            this.tblChiTietHDBans = new HashSet<tblChiTietHDBan>();
            this.tblChiTietHDNhaps = new HashSet<tblChiTietHDNhap>();
        }
    
        public string Mahang { get; set; }
        public string Tenhang { get; set; }
        public string maLoai { get; set; }
        public Nullable<double> Soluong { get; set; }
        public Nullable<double> Dongianhap { get; set; }
        public Nullable<double> Dongiaban { get; set; }
        public string Anh { get; set; }
        public string Ghichu { get; set; }
    
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietHDBan> tblChiTietHDBans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietHDNhap> tblChiTietHDNhaps { get; set; }
    }
}
